log_filter: info,waitingway_web=debug,tracing::span=warn,serenity::gateway::shard=warn,serenity::http=warn
server_addr: 0.0.0.0:3000
downloader:
  storage_dir: downloads
  slug: 4e9a232b
  file_regex: '^sqpack\/ffxiv\/0a0000\..+$'
  parallelism: 4
  clut_path: "https://raw.githubusercontent.com/WorkingRobot/ffxiv-downloader/refs/heads/main/cluts"
